config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

	validates :title, presence: true, length: {minimum: 5}
	validates :venue, presence: true
	validates :location, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :set_event,only: [:show, :edit,:update, :destroy]

	def index
		@events = Event.all
	end
	
	def show
		
	end

	

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			flash[:notice] = "Event created!"
			redirect_to @event
		else
			flash.now[:alert] = "Event not created"
			render "new"
		end
	end

	
	def edit
		
	end

	def update
		

		if @event.update(event_params)
			flash[:notice] = "event updated!"
			redirect_to @event
		else
			flash.now[:alert] = "event not updated!"
			render "edit"
		end
	end

	def destroy
		
		@event.destroy
		flash[:alert] = "Event deleted successfully"
		redirect_to event_url
	end


	private

	  def set_event
	  	@event = Event.find(params[:id])

	  rescue ActiveRecord::RecordNotFound
	  	flash.keep[:alert] = "The page you just requested does not exist"
	  	redirect_to events_path
	  end

	  def event_params
	  	params.require(:event).permit(:title, :description, :start_date, :end_date, :venue, :location)
      end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		default_title = "Eventsboard"
		if page_title.empty?
			default_title
		else
			"#{page_title} | #{default_title}"
		end
	end

	def time_format(event_date)
		event_date.strftime("%A, %d %b %Y %l:%M %p")
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb


<%= simple_form_for(event) do |f| %>
	<%= f.input :title%>

	<%= f.input :description %>
	<%= f.input :start_date, as: :datetime, start_year: Date.today.year, ampm: true, order: [:day, :month, :year] %>

	<%= f.input :end_date, as: :datetime, start_year: Date.today.year, ampm: true, order: [:day, :month, :year] %>


  <%= f.input :venue %>
  <%= f.input :location %>


	<%= f.button :submit, class: "btn bth-primary" %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<h1>All events</h1>

<p><%= link_to "Add Event", new_event_path %></p>

<% @events.each do |e| %>
  <div>
	<h4><%= link_to e.title, e %></h4>
	<p><%= time_format(e.start_date) %> <%= fa_icon "camera-retro" %></p>
	<p><%= time_format(e.end_date) %></p>
	<p><%= e.venue %>, <%= e.location %></p>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>New events</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>

<h1><%= @event.title %></h1>

<div>
	<p><%= @event.description %></p>
	<p><%= time_format(@event.start_date) %></p>
	<p><%= time_format(@event.end_date) %></p>
	<p><%= @event.venue %></p>
	<p><%= @event.location %></p>
</div>

<p>
	<%= link_to "Edit Event", edit_event_path(@event) %> | <%= link_to "Delete Event", event_path(@event), method: :delete, data: {confirm: "Are you sure?"} %>


</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:alert] %>
      <div id="alert">
         <%= flash[:alert] %> 
      </div>
   <% end %>
   <div class = "container">
    <%= yield %>
    </div>
  </body>
</html>